package hibernate;
// Generated Apr 1, 2015 5:23:03 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String displayName;
     private String email;
     private String mobile;
     private String fullName;
     private byte[] profileImage;
     private String password;

    public User() {
    }

	
    public User(String mobile, String password) {
        this.mobile = mobile;
        this.password = password;
    }
    public User(String displayName, String email, String mobile, String fullName, byte[] profileImage, String password) {
       this.displayName = displayName;
       this.email = email;
       this.mobile = mobile;
       this.fullName = fullName;
       this.profileImage = profileImage;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public byte[] getProfileImage() {
        return this.profileImage;
    }
    
    public void setProfileImage(byte[] profileImage) {
        this.profileImage = profileImage;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


